# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-12-10 04:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LifeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日期')),
                ('consumption_matters', models.CharField(max_length=20, verbose_name='消费事项')),
                ('amount', models.IntegerField(verbose_name='消费金额')),
                ('total', models.IntegerField(verbose_name='月度总计消费')),
            ],
            options={
                'db_table': 'tb_life',
            },
        ),
    ]
