# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-12-10 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumption', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lifeinfo',
            options={'verbose_name': '历史消费记录', 'verbose_name_plural': '历史消费记录'},
        ),
        migrations.AlterField(
            model_name='lifeinfo',
            name='total',
            field=models.IntegerField(verbose_name='总计消费'),
        ),
    ]
